//! Embedded Nyx verifying key (from circuits/verification_key.json).
//!
//! The key is embedded as raw bytes generated by `scripts/proof_to_bytes.js`
//! (the single source of truth for the snarkjs-decimal -> BN254 byte
//! conversion). Embedding keeps the wasm self-contained and purpose-built for
//! the Nyx darkpool circuit. If the circuit is recompiled, re-run the script to
//! regenerate these fixtures, then rebuild + redeploy.

use soroban_sdk::crypto::bn254::{Bn254G1Affine, Bn254G2Affine};
use soroban_sdk::{vec, BytesN, Env, Vec};

const ALPHA_G1: &[u8; 64] = include_bytes!("../test_vectors/vk_alpha_g1.bin");
const BETA_G2: &[u8; 128] = include_bytes!("../test_vectors/vk_beta_g2.bin");
const GAMMA_G2: &[u8; 128] = include_bytes!("../test_vectors/vk_gamma_g2.bin");
const DELTA_G2: &[u8; 128] = include_bytes!("../test_vectors/vk_delta_g2.bin");
const IC0_G1: &[u8; 64] = include_bytes!("../test_vectors/vk_ic0_g1.bin");
const IC1_G1: &[u8; 64] = include_bytes!("../test_vectors/vk_ic1_g1.bin");
const IC2_G1: &[u8; 64] = include_bytes!("../test_vectors/vk_ic2_g1.bin");

fn g1(env: &Env, bytes: &[u8; 64]) -> Bn254G1Affine {
    Bn254G1Affine::from_bytes(BytesN::from_array(env, bytes))
}

fn g2(env: &Env, bytes: &[u8; 128]) -> Bn254G2Affine {
    Bn254G2Affine::from_bytes(BytesN::from_array(env, bytes))
}

/// Returns (alpha_g1, beta_g2, gamma_g2, delta_g2, ic) where ic has nPublic+1 = 3 points.
pub fn load(
    env: &Env,
) -> (
    Bn254G1Affine,
    Bn254G2Affine,
    Bn254G2Affine,
    Bn254G2Affine,
    Vec<Bn254G1Affine>,
) {
    let ic = vec![env, g1(env, IC0_G1), g1(env, IC1_G1), g1(env, IC2_G1)];
    (
        g1(env, ALPHA_G1),
        g2(env, BETA_G2),
        g2(env, GAMMA_G2),
        g2(env, DELTA_G2),
        ic,
    )
}
